/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class PlotPanels_PlotPanel */

#ifndef _Included_PlotPanels_PlotPanel
#define _Included_PlotPanels_PlotPanel
#ifdef __cplusplus
extern "C" {
#endif
#undef PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_UNKNOWN
#define PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_DEFAULT
#define PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_SET
#define PlotPanels_PlotPanel_FOCUS_TRAVERSABLE_SET 2L
#undef PlotPanels_PlotPanel_TOP_ALIGNMENT
#define PlotPanels_PlotPanel_TOP_ALIGNMENT 0.0f
#undef PlotPanels_PlotPanel_CENTER_ALIGNMENT
#define PlotPanels_PlotPanel_CENTER_ALIGNMENT 0.5f
#undef PlotPanels_PlotPanel_BOTTOM_ALIGNMENT
#define PlotPanels_PlotPanel_BOTTOM_ALIGNMENT 1.0f
#undef PlotPanels_PlotPanel_LEFT_ALIGNMENT
#define PlotPanels_PlotPanel_LEFT_ALIGNMENT 0.0f
#undef PlotPanels_PlotPanel_RIGHT_ALIGNMENT
#define PlotPanels_PlotPanel_RIGHT_ALIGNMENT 1.0f
#undef PlotPanels_PlotPanel_serialVersionUID
#define PlotPanels_PlotPanel_serialVersionUID -7644114512714619750LL
#undef PlotPanels_PlotPanel_serialVersionUID
#define PlotPanels_PlotPanel_serialVersionUID -2284879212465893870LL
#undef PlotPanels_PlotPanel_PERIOD
#define PlotPanels_PlotPanel_PERIOD 100L
/*
 * Class:     PlotPanels_PlotPanel
 * Method:    paintOpenGLVoid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_PlotPanels_PlotPanel_paintOpenGLVoid
  (JNIEnv *, jobject, jint);

/*
 * Class:     PlotPanels_PlotPanel
 * Method:    initializeGL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlotPanels_PlotPanel_initializeGL
  (JNIEnv *, jobject);

/*
 * Class:     PlotPanels_PlotPanel
 * Method:    releaseGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PlotPanels_PlotPanel_releaseGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
